allowedDomains: []
customUrls:
  cdn: ""
  api: ""
validateOnLastPageOnly: false
header:
  content: ""
  _id: 656ed5d133a01e5213efdeb8
theme:
  language: en
  palette:
    light:
      primary:
        main: "#00376c"
        light: rgb(51, 95, 137)
        dark: rgb(0, 38, 75)
        contrastText: "#fff"
    primary:
      main: "#263160"
      light: rgb(81, 90, 127)
      dark: rgb(26, 34, 67)
      contrastText: "#fff"
pageDependencies:
  20904f70-f980-4d6b-afa1-f7d6b652013f: []
  36ae9480-c072-4b6e-963b-5aef4dcaffd4:
    - value: 41f99ef1-6886-40cc-bb33-440e10825596
      label: "1.1"
  8f19c2f7-5e0e-435f-b428-b89e5f68702b: []
  7e121e76-8e1c-416e-8198-03a9cb173638: []
  cb5d45f3-f2c7-4d0c-8311-0b4e720b88c2: []
pagesToForceValidate:
  41f99ef1-6886-40cc-bb33-440e10825596: 41f99ef1-6886-40cc-bb33-440e10825596
stepper:
  stepperType: vertical
  stepperAlignment: left
  subStepType:
    label: Dots
    value: dots
  steps:
    - label: Personal Information
      value: 6bd3dc56-d50b-4247-b172-3f081e463477
      page: 36ae9480-c072-4b6e-963b-5aef4dcaffd4
      numOfSubSteps: null
    - label: Health Questionnaire
      value: b86db3b5-a43b-419a-bfe5-21ab03ffd6c3
      page: 41f99ef1-6886-40cc-bb33-440e10825596
      numOfSubSteps: 3
    - label: Summary
      value: 0af94ee4-4e75-4209-a6ba-9e386044fb6b
      page: 36ae9480-c072-4b6e-963b-5aef4dcaffd4
      numOfSubSteps: null
  keysToDisableNavigation: []
  disabledSteps: []
  isSubSteps: true
  isConnectorsActive: false
  isAlternativeLabel: false
  customCss: "/*.cs-stepper-stepLabel-root {\r

    \  height: 50px;\r

    \  background-color: white;\r

    \  margin-bottom: 2px;\r

    \  border: 1px solid #b6b6b7;\r

    \  }\r

    \  \r

    \  & .MuiStepConnector-root\r

    {\r

    \  display: none;\r

    }"
variables:
  submissionData:
    7709e8cb-d7d1-4019-9a51-36aaae77c0cb:
      name: textfield-408
      id: 7709e8cb-d7d1-4019-9a51-36aaae77c0cb
      dataType: text
      varType: submissionData
    928fe0cb-8d19-41b8-ac0b-185f4fb67fcb:
      name: firstname
      id: 928fe0cb-8d19-41b8-ac0b-185f4fb67fcb
      dataType: text
      varType: submissionData
    1f73cf9d-c886-411f-a7b6-b459d3d6d917:
      name: lastname
      id: 1f73cf9d-c886-411f-a7b6-b459d3d6d917
      dataType: text
      varType: submissionData
    f4a473a5-4138-40c8-98ad-e5d525f5a58c:
      name: title
      id: f4a473a5-4138-40c8-98ad-e5d525f5a58c
      dataType: text
      varType: submissionData
    e98e4957-f522-468e-be0c-ef4d64fc2b2a:
      name: dob
      id: e98e4957-f522-468e-be0c-ef4d64fc2b2a
      dataType: date
      varType: submissionData
    3a4413a3-af12-4701-a55f-b26157919c46:
      name: weight
      id: 3a4413a3-af12-4701-a55f-b26157919c46
      dataType: text
      varType: submissionData
    98a3c733-1d6f-459a-9a07-4caf09f1b5f7:
      name: height
      id: 98a3c733-1d6f-459a-9a07-4caf09f1b5f7
      dataType: text
      varType: submissionData
    868c15e9-6eab-4afb-b03c-a3df00dd9497:
      name: smoke
      id: 868c15e9-6eab-4afb-b03c-a3df00dd9497
      dataType: text
      varType: submissionData
    60700726-546a-4fd3-8a2c-fbd7e5ac40c2:
      name: history
      id: 60700726-546a-4fd3-8a2c-fbd7e5ac40c2
      dataType: text
      varType: submissionData
